config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :ticket, only: [] do
        get :buy, on: :member
      end
    end
  end
  devise_for :users
  resources :prizes
  resources :tickets
  resources :raffles
  resource :raffle, only: [] do
    member do
      get :create_tickets
    end
  end
  resources :users
  resource :user, only: [] do
    member do
      get :dashboard
    end
  end
  resources :types
  root to: 'raffles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/raffle.rb
class Raffle < ApplicationRecord
  belongs_to :user
  belongs_to :type
  has_many :prizes
  has_many :tickets

end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  before_action :set_raffle, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  # GET /raffles
  def index
    @search = params[:search]

    @raffles = Raffle.all.includes(:tickets, :type, :user)
                     .left_joins(:prizes)
                     .group('raffles.id')

    @raffles = @raffles.where('raffles.title LIKE ?', "%#{@search[:title]}%") if @search && !@search[:title].blank?
  end

  # GET /raffles/1
  def show
    @raffle.tickets = @raffle.tickets.paginate(page: params[:page] || 1, per_page: 100)
  end

  # GET /raffles/new
  def new
    @raffle = Raffle.new
  end

  # GET /raffles/1/edit
  def edit; end

  # POST /raffles
  def create
    @raffle = Raffle.new(raffle_params)

    if @raffle.save
      CreateTicketsJob.perform_later(@raffle)
      redirect_to @raffle, notice: 'Raffle was successfully created. Tickets being created'
    else
      render :new
    end
  end

  # PATCH/PUT /raffles/1
  def update
    if @raffle.update(raffle_params)
      redirect_to @raffle, notice: 'Raffle was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /raffles/1
  def destroy
    @raffle.destroy
    redirect_to raffles_url, notice: 'Raffle was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_raffle
    @raffle = Raffle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def raffle_params
    params.require(:raffle).permit(:user_id, :type_id, :title, :description, :probable_draw_date, :start_date_sale,
                                   :end_date_sale, :draw_date, :ticket_value)
  end
end

app/helpers/raffles_helper.rb
module RafflesHelper
end

app/views/raffles/_form.html.erb
<%= simple_form_for @raffle do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :type %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :probable_draw_date %>
    <%= f.input :start_date_sale %>
    <%= f.input :end_date_sale %>
    <%= f.input :draw_date %>
    <%= f.input :ticket_value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Raffle' : 'Update Raffle', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/raffles/edit.html.erb
<% content_for :title do %>
  Edit Raffle
<% end %>

<div class="page-header">
  <h1>Edit Raffle</h1>
  <div>
    <%= link_to @raffle, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Show
    <% end %>
    <%= link_to new_type_path, class: 'btn btn-warning' do %>
      <%= icon 'fas', 'plus' %>
      Add Type
    <% end %>
    <%= link_to new_prize_path, class: 'btn btn-success' do %>
      <%= icon 'fas', 'plus' %>
      Add Prize
    <% end %>
    <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/raffles/index.html.erb
<% content_for :title do %>
  Raffles
<% end %>

<div class="page-header">
  <% if user_signed_in? %>
  <%= link_to new_raffle_path, class: 'btn btn-secondary ' do %>
    <%= icon 'fas', 'plus' %>
    New Raffle
  <% end %>
  <% end %>
</div>

<div class="card-columns">
  <% @raffles.each do |raffle| %>
    <div class="card border-secondary" style="max-width: 18rem;">
    <div class="card-header"><%=raffle.title%></div>
      <div class="card-body">
        <h5 class="card-title"><%=raffle.type%></h5>
        <p class="card-text"><%= raffle.description%></p>
        <%= link_to raffle, class: 'btn btn-info btn-sm' do %>
          <%= icon 'fas', 'eye', class: 'fa-fw' %>
        <% end %>
        <% if user_signed_in?  %>
        <% if current_user == raffle.user  %>
        <%= link_to edit_raffle_path(raffle), class: 'btn btn-success btn-sm' do %>
          <%= icon 'fas', 'edit', class: 'fa-fw' %>
        <% end %>
        <%= link_to raffle, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
          <%= icon 'fas', 'times', class: 'fa-fw' %>
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/raffles/new.html.erb
<% content_for :title do %>
  New Raffle
<% end %>

<div class="page-header">
  <h1>New Raffle</h1>
  <div>
  <%= link_to new_type_path, class: 'btn btn-warning' do %>
    <%= icon 'fas', 'plus' %>
    Add Type
  <% end %>
  <%= link_to new_prize_path, class: 'btn btn-success' do %>
    <%= icon 'fas', 'plus' %>
    Add Prize
  <% end %>
  <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/raffles/show.html.erb
<% content_for :title do %>
  Raffle's Details
<% end %>


<div class="card border-secondary">
<div class="card-header">
  <div class="d-flex justify-content-between">
  <div><h4 class="card-title"><%= @raffle.title%></h4></div>
  <div>  
    <% if current_user == @raffle.user  %>
    <%= link_to edit_raffle_path(@raffle), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <% end %>
    <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
    </div>
  </div>
</div>
<div class="card-body">
    
    <h4 class="card-text">Value: <%= @raffle.ticket_value%></h4>
    <h5 class="card-text">Creator: <%= @raffle.user.name%></h5>
    <h6 class="card-text">Stard Sale: <%= @raffle.start_date_sale.strftime("%T %F")%></h6>
    <h6 class="card-text">End Sale: <%= @raffle.end_date_sale.strftime("%T %F")%></h6>
    <h6 class="card-text">Draw: <%= @raffle.draw_date.strftime("%T %F")%></h6>
    <p class="card-text">Description: <%= @raffle.description%></p>
    
  </div>
  </div>
  <h5 class='page-header'>Prizes: </h5>
<div class="card-columns">
  <% @raffle.prizes.each do |prize| %>
    <div class="card bg-warning mb-3" style="max-width: 18rem;">
    <div class="card-header">Placing: <%=prize.placing%></div>
      <div class="card-body">
        <p class="card-text">Prize: <%= prize.description%></p>
        <%= link_to prize, class: 'btn btn-outline-info btn-sm' do %>
          <%= icon 'fas', 'eye', class: 'fa-fw' %>
        <% end %>
        <% if user_signed_in?  %>
        <% if current_user == @raffle.user  %>
        <%= link_to edit_prize_path(prize), class: 'btn btn-outline-success btn-sm' do %>
          <%= icon 'fas', 'edit', class: 'fa-fw' %>
        <% end %>
        <%= link_to prize, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-outline-danger btn-sm' do %>
          <%= icon 'fas', 'times', class: 'fa-fw' %>
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<h5 class='page-header'>Tickets: </h5>
<div class="card-columns">
  <% @raffle.tickets.each do |ticket| %>
  <% if ticket.user%>
    <div class="card bg-secondary mb-3" style="max-width: 18rem;">
  <% else %>
    <div class="card bg-light mb-3" style="max-width: 18rem;">
  <%end%>
    <div class="card-header">Raffle: <%=ticket.raffle.title%></div>
      <div class="card-body">
      <div class="d-flex justify-content-center">
        <% if ticket.user %>
        <p class="card-text"><%= ticket.number%></p>
        <%end%>
        </div>
        <div class="d-flex justify-content-around">
        <% if !ticket.user %>
        <%= link_to ticket, ticket_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modalBuy', class: 'btn btn-info btn-md'}  %>
        <div id="modalBuy" class="modal hide fade" role="dialog" aria-labelledby="buyTicket" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form-horizontal" action = "<%= buy_api_v1_ticket_path(ticket)%>"id="formBuy">
                  <h5 class="modal-header"><b>Buy Ticket?</b></h5>

                    <div class="modal-header">
                        <div class="form-group">
                          <div class='row'>
                              <div class='col-sm-12'>
                                  <label><b>Number</b></label>
                                  <input type="text" class="form-control" value=<%= ticket.number%> readonly>
                              </div>
                              <div class='col-sm-12'>
                                  <label><b>Price</b></label>
                                  <input type="text" class="form-control" value=<%= @raffle.ticket_value%> readonly>
                              </div>
                              <div class='col-sm-12'>
                                  <label><b>Draw Date</b></label>
                                  <input type="text" class="form-control" value=<%= @raffle.draw_date%> readonly>
                              </div>
                              </div>
                          </div>    
                      </div>
                    <div class="modal-footer">
                        <button id="btn-buy-ticket" type="submit" class="btn btn-success btn-sm">YES!</button>
                        <button type="cancel" class="btn btn-danger btn-sm" data-dismiss="modal">NOP</button>
                    </div>
                </form>
            </div>
        </div>
        </div>
          
          <% end %>
      </div>
      </div>
    </div>
  <% end %>
   
</div>