config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :ticket, only: [] do
        get :buy, on: :member
      end
    end
  end
  devise_for :users
  resources :prizes
  resources :tickets
  resources :raffles
  resource :raffle, only: [] do
    member do
      get :create_tickets
    end
  end
  resources :users
  resource :user, only: [] do
    member do
      get :dashboard
    end
  end
  resources :types
  root to: 'raffles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  def index
    @types = Type.all
  end

  # GET /types/1
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  def create
    @type = Type.new(type_params)

    if @type.save
      redirect_to @type, notice: 'Type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /types/1
  def update
    if @type.update(type_params)
      redirect_to @type, notice: 'Type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /types/1
  def destroy
    @type.destroy
    redirect_to types_url, notice: 'Type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:description, :inicial_number, :step, :ticket_quantities)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= simple_form_for @type do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :inicial_number %>
    <%= f.input :step %>
    <%= f.input :ticket_quantities %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Type' : 'Update Type', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<% content_for :title do %>
  Edit Type
<% end %>

<div class="page-header">
  <h1>Edit Type</h1>
  <div>
    <%= link_to @type, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Show
    <% end %>
    <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/types/index.html.erb
<% content_for :title do %>
  Types
<% end %>

<div class="page-header">
  <h1>Types</h1>
  <%= link_to new_type_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New Type
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Inicial number</th>
        <th>Step</th>
        <th>Ticket quantities</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @types.each do |type| %>
        <tr>
          <td><%= type.description %></td>
          <td><%= type.inicial_number %></td>
          <td><%= type.step %></td>
          <td><%= type.ticket_quantities %></td>
          <td>
            <%= link_to type, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_type_path(type), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to type, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/types/new.html.erb
<% content_for :title do %>
  New Type
<% end %>

<div class="page-header">
  <h1>New Type</h1>
  <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/types/show.html.erb
<% content_for :title do %>
  Type's Details
<% end %>

<div class="page-header">
  <h1>Type's Details</h1>
  <div>
    <%= link_to edit_type_path(@type), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to types_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @type.description %></dd>

  <dt>Inicial number:</dt>
  <dd><%= @type.inicial_number %></dd>

  <dt>Step:</dt>
  <dd><%= @type.step %></dd>

  <dt>Ticket quantities:</dt>
  <dd><%= @type.ticket_quantities %></dd>

</dl>