config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :ticket, only: [] do
        get :buy, on: :member
      end
    end
  end
  devise_for :users
  resources :prizes
  resources :tickets
  resources :raffles
  resource :raffle, only: [] do
    member do
      get :create_tickets
    end
  end
  resources :users
  resource :user, only: [] do
    member do
      get :dashboard
    end
  end
  resources :types
  root to: 'raffles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tickets
  has_many :raffles
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def dashboard
    @raffles = current_user.raffles
    @tickets = current_user.tickets
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :photo, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :photo %>
    <%= f.input :admin %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Criar User' : 'Atualizar User', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= simple_form_for :search, url: raffles_path, method: :get, html: { class: 'align-middle', style: 'max-width: 15rem;' } do |f|%>
    <%= f.input :title, 
    input_html: {value: @search ? @search[:title] : ''}, 
    class: 'form-control mr-sm-2',
    placeholder: 'Search', 
    label: false %>
<% end %>

app/views/users/dashboard.html.erb
<div class="page-header">
    <div><%= link_to new_raffle_path, class: 'btn btn-secondary ' do %> 
  <%= icon 'fas', 'plus' %> New Raffle <% end %> 
  <%= link_to raffles_path, class: 'btn  btn-success ' do   %>
  <%= icon 'fas', 'plus' %> Buy Tickets! <% end %></div>
  
  <h5>Welcome to your Dashboard, <%= current_user.name %>!</h5>
</div>

<div class="card">
  <div
    style="color: white"
    class="h4 card-header bg-warning d-flex justify-content-around"
  >
    <div>Your Tickets!</div>
    <div><%= @tickets.count %> purchased</div>
  </div>
  <div class="card-body">
    <div class="card-columns">
      <% @tickets.each do |ticket| %>
      <div class="card border-warning">
        <h5 class="card-header">Raffle: <%=ticket.raffle.title%></h5>
        <div class="card-body">
          <p class="card-text text-center"><%= ticket.number%></p>
          <p class="card-text text-center"><%= ticket.raffle.description%></p>
          <p class="card-text text-center">
            Draw Date: <%= ticket.raffle.draw_date.to_formatted_s%>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="card mt-4">
  <h4 style="color: white" class="card-header bg-danger text-center">
    Raffles you started!
  </h4>
  <div class="card-body">
    <div class="card-columns">
      <% @raffles.each do |raffle| %>
      <div class="card border-danger">
        <div class="card-header text-center"><%=raffle.title%></div>
        <div class="card-body text- center">
          <h5 class="card-title text-center"><%=raffle.type%></h5>
          <p class="card-text text-center"><%= raffle.description%></p>
          <div class="d-flex justify-content-between">
            <%= link_to raffle, class: 'btn btn-info btn-sm' do %> 
            <%= icon 'fas', 'eye', class: 'fa-fw' %>  <% end %>
            <%= link_to edit_raffle_path(raffle), class: 'btn btn-success btn-sm' do %> 
            <%= icon 'fas', 'edit', class: 'fa-fw' %> <% end %>
            <%= link_to raffle, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn
            btn-danger btn-sm' do %> 
            <%= icon 'fas', 'times', class: 'fa-fw' %>  <% end %> 
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title do %>
  Editando User
<% end %>

<div class="page-header">
  <h1>Editando User</h1>
  <div>
    <%= link_to @user, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Ver
    <% end %>
    <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :title do %>
  Users
<% end %>

<div class="page-header">
  <h1>Users</h1>
  <%= link_to new_user_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Novo User
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Photo</th>
        <th>Admin</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.password %></td>
          <td><%= user.photo %></td>
          <td><%= user.admin %></td>
          <td>
            <%= link_to user, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_user_path(user), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to user, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
  Novo User
<% end %>

<div class="page-header">
  <h1>Novo User</h1>
  <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :title do %>
  Detalhes de User
<% end %>

<div class="page-header">
  <h1>Detalhes de User</h1>
  <div>
    <%= link_to edit_user_path(@user), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @user.name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

  <dt>Password:</dt>
  <dd><%= @user.password %></dd>

  <dt>Photo:</dt>
  <dd><%= @user.photo %></dd>

  <dt>Admin:</dt>
  <dd><%= @user.admin %></dd>

</dl>