config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :ticket, only: [] do
        get :buy, on: :member
      end
    end
  end
  devise_for :users
  resources :prizes
  resources :tickets
  resources :raffles
  resource :raffle, only: [] do
    member do
      get :create_tickets
    end
  end
  resources :users
  resource :user, only: [] do
    member do
      get :dashboard
    end
  end
  resources :types
  root to: 'raffles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :raffle
  belongs_to :user, optional: true
  has_many :prizes

  def to_s
    number
  end
end

app/controllers/api/v1/ticket_controller.rb
class Api::V1::TicketController < Api::V1::ApplicationController
  before_action :authenticate_user!

  def buy
    @ticket = Ticket.find(params[:id])
    if @ticket.update(user: current_user)
      redirect_to raffle_path(@ticket.raffle)
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  # GET /tickets
  def index
    @tickets = Ticket.all.includes(:user, :raffle)
  end

  # GET /tickets/1
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.user = current_user
  end

  # GET /tickets/1/edit
  def edit; end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:raffle_id, :user_id, :number)
  end
end

app/helpers/api/v1/ticket_helper.rb
module Api::V1::TicketHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :raffle %>
    <%= f.association :user %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Ticket' : 'Update Ticket', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<% content_for :title do %>
  Edit Ticket
<% end %>

<div class="page-header">
  <h1>Edit Ticket</h1>
  <div>
    <%= link_to @ticket, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Show
    <% end %>
    <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/tickets/index.html.erb
<% content_for :title do %>
  Tickets
<% end %>

<div class="page-header">
  <h1>Tickets</h1>
  <%= link_to new_ticket_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New Ticket
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Raffle</th>
        <th>Number</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.raffle.description %></td>
          <td><%= ticket.number %></td>
          <td>
            <%= link_to ticket, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_ticket_path(ticket), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to ticket, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/new.html.erb
<% content_for :title do %>
  New Ticket
<% end %>

<div class="page-header">
  <h1>New Ticket</h1>
  <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/tickets/show.html.erb
<% content_for :title do %>
  Ticket's Details
<% end %>

<div class="page-header">
  <h1>Ticket's Details</h1>
  <div>
    <%= link_to edit_ticket_path(@ticket), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Raffle:</dt>
  <dd><%= @ticket.raffle.description %></dd>

  <dt>Number:</dt>
  <dd><%= @ticket.number %></dd>

  <% if @ticket.user%>
  <dt>User:</dt>
  <dd><%= @ticket.user.name %></dd>
  
  <% end %>

</dl>